### ISSUE TITLE
No circuit diagram for breadboard DIY two-chip level shifter

### ISSUE THREAD

**Issue by damieng** [hoglet67/PiTubeDirect#1]
I can't seem to find the wiring diagram for this anywhere in the wiki or code.

**Comment by hoglet67** [comment]
The current schematic and PCB layout is checked into git here:
https://github.com/hoglet67/PiTubeDirect/tree/master/kicad

There are also active discussions about level shifter on stardot here:
http://www.stardot.org.uk/forums/viewtopic.php?f=3&t=11444

**Comment by damieng** [comment]
I'll take a look at those and see if I can get up and running, thanks!
