### ISSUE TITLE
cppcheck warning f100_debug.c

### ISSUE THREAD

**Issue by dp111** [hoglet67/PiTubeDirect#110]
[C:/linux/PiTubeDirect-gecko-dev/src/f100/f100_debug.c:489] (warning) %x in format string (no. 1) requires 'unsigned int *' but the argument type is 'signed int *'. [invalidScanfArgType_int]

[C:/linux/PiTubeDirect-gecko-dev/src/f100/f100_debug.c:489] (warning) %x in format string (no. 2) requires 'unsigned int *' but the argument type is 'signed int *'. [invalidScanfArgType_int]

Line 489 : sscanf(start, "%x,%x", &data_start, &data_end);

**Comment by hoglet67** [comment]
This one should be fixed now.
