### ISSUE TITLE
Native ARM Co Pro: Add Pi Type to OSBYTE A=00 Response

### ISSUE THREAD

**Issue by hoglet67** [hoglet67/PiTubeDirect#121]
Native ARM Co Pro: Add Pi Type to OSBYTE A=-00 Response

So native code running on the Pi can use an appropriate IO address

e.g. for Audio

**Comment by jgharston** [comment]
OSBYTE 0 always returns what the *host* system is, not what the CoPro is. Changing this would break literally millions of programs.

The appropriate method for the client to find what sort of client it is is for a client-specific call. In this case, some sort of SWI call, probably OS_PlatformFeatures. (OS_PlatformFeatures reads hardware info, OS_ReadSysInfo reads software info, o OS_PlatformFeatures is more appropriate.)

**Comment by hoglet67** [comment]
Closing as won't fix.
