### ISSUE TITLE
80x86 Co Pro: Issues with IDIV

### ISSUE THREAD

**Issue by hoglet67** [hoglet67/PiTubeDirect#127]
From Dominic:

Just looking over warnings for various code checkers . Does anyone know an x86 checker like dormann ? I think cpu80186.c line 1124 has a bug. it looks as though it is written for a 16 bit divide where as it should be an 8 bit divide. line 1143 I think needs to be reinstated bit with (s2 < 0x80)? s2 :....

https://github.com/hoglet67/PiTubeDirect/blob/6e10b31991d06468f07a98120dcbdba19f73dc6b/src/cpu80186/cpu80186.c#L1143

This would be a long-standing fake86 bug.

**Comment by hoglet67** [comment]
There is also a bug in this line:
https://github.com/hoglet67/PiTubeDirect/blob/6e10b31991d06468f07a98120dcbdba19f73dc6b/src/cpu80186/cpu80186.c#L1141

I wonder if the best solution is to just sign-extend the divisor to 16 bits.

i.e. instead of
```
  s2 = divisor
```
have
```
  s2 = divisor;
  if (s2 & 0x80) {
    s2 |= 0xff00;
  }
```
Then both s1 and s2 are 16 bits, and the code should be the same as the 16-bit version.

**Comment by dp111** [comment]
looks sensible : https://www.felixcloutier.com/x86/idiv

**Comment by hoglet67** [comment]
There may be a second issue with idiv.

The documentation states:

> Non-integral results are truncated (chopped) towards 0. 

I believe the implication of this is that the sign of the remainder should depend only on the sign of the dividend:

```
 13 / 4 : quotient =  3 remainder =   1    (checking:  3* 4+1= 13)  
 13 /-4 : quotient = -3 remainder =   1    (checking: -3*-4+1= 13)
-13 / 4 : quotient = -3 remainder =  -1    (checking: -3* 4-1=-13)
-13 /-4 : quotient =  3 remainder =  -1    (checking:  3*-4-1=-13)
```
I don't believe the current code is correct in this respect...
```
  if (sign)
  {
    d1 = (~d1 + 1) & 0xff;
    d2 = (~d2 + 1) & 0xff;
  }
```
It looks like the current code always makes the sign of the quotient (d1) and remainder (d2) the same.

I really need to try write some test cases, and maybe get someone to run them on a real 80186 Co Pro.

**Comment by hoglet67** [comment]
Here's a small test case for IDIV8:
![capture25](https://user-images.githubusercontent.com/1951463/139576596-bc62b15d-872a-4524-95e7-bbb33633f0cf.png)
Here's the (correct) result from the Matchbox Co Pro:
![capture26](https://user-images.githubusercontent.com/1951463/139576639-63cff075-76ad-438f-a6b8-38021fc51613.png)
Here's the (incorrect) result from PiTubeDirect Alpha4:
![capture27](https://user-images.githubusercontent.com/1951463/139576658-42d5e8ba-8d32-4ed9-8ae3-86cf63b9a829.png)
And here's the result after the fix:
![capture28](https://user-images.githubusercontent.com/1951463/139576665-3622bec8-92e1-4687-83a8-81b0c968581d.png)

**Comment by hoglet67** [comment]
Here's a small test case for IDIV16:
![capture30](https://user-images.githubusercontent.com/1951463/139576673-691d2c6c-8058-4eb2-9f1f-7e0a708593d9.png)
Here's the (correct) result from the Matchbox Co Pro:
![capture31](https://user-images.githubusercontent.com/1951463/139576695-f5ee3080-3304-45db-89f1-cfbc983866d0.png)
Here's the (incorrect) result from PiTubeDirect Alpha4:
![capture32](https://user-images.githubusercontent.com/1951463/139576717-2669945e-8e26-474c-b067-0cbd639274c9.png)
And here's the result after the fix:
![capture33](https://user-images.githubusercontent.com/1951463/139576731-749dedba-6d7f-4866-a89a-0057e9e82453.png)

**Comment by hoglet67** [comment]
Dominic, if you get the chance, could you run the updated code through cppcheck?
