### ISSUE TITLE
Frame Buffer: top line of triangle not being plotted

### ISSUE THREAD

**Issue by mincebert** [hoglet67/PiTubeDirect#131]
In graphics mode (MODE 2's colours make it obvious) do:

GCOL 0,1:REM to see what's being plotted
MOVE 0,0
MOVE 0,1023
PLOT 85,100,1023

... the top row of pixels aren't plotted.

If you then plot the triangle with the pointy end at 1023, it does plot the pixel, e.g.:

GCOL 0,2
MOVE 0,0
MOVE 100,0
PLOT 85,100,1023

This is different to the MOS’s normal rendering, so plotting two back-to-back triangles doesn’t give a clean square.

I can attach some screenshots if necessary, but it should be obvious from above.

**Comment by hoglet67** [comment]
Thanks for this.

I understand why this is happening and it should be fixable.
