### ISSUE TITLE
JIT 6502: Hangs on Pi 4

### ISSUE THREAD

**Issue by hoglet67** [hoglet67/PiTubeDirect#142]
Alpha4 works file, Beta1 hangs at the language transfer.

Bisecting shows this is the commit that breaks things: ec8d836c (improve a53 I cache flush)

I have no idea how to start debugging this, because I don't understand the details of what is being flushed here, and why it's got so complicated.

**Comment by dp111** [comment]
Let back out that commit and I'll look at it in more detail for the next
release.

**Comment by hoglet67** [comment]
OK, I'll revert that commit.

**Comment by hoglet67** [comment]
Reverted....
