### ISSUE TITLE
Add to Call &2000 to some method to highlight which 65C02 is running.

### ISSUE THREAD

**Issue by dp111** [hoglet67/PiTubeDirect#148]

**Comment by dp111** [comment]
Also add copro number to the PiVDU screen and the sphere REM statements

**Comment by hoglet67** [comment]
How do the following look?

![capture2](https://user-images.githubusercontent.com/1951463/148218156-d826d52c-cb80-4b1d-b8f3-97c4b89b2c8b.png)
![capture1](https://user-images.githubusercontent.com/1951463/148218150-f2c36b33-4619-4a24-b75e-d141cbea2263.png)
![capture0](https://user-images.githubusercontent.com/1951463/148218131-67517a66-c405-4236-bb34-0dccf941d58e.png)
![my_photo-1](https://user-images.githubusercontent.com/1951463/148218404-2b579808-51fe-49c9-a6d5-7acb1617c485.jpg)

**Comment by dp111** [comment]
Looks excellent to me.

**Comment by hoglet67** [comment]
The splash screen is now redrawn when you switch Co Pros (previously it was only drawn once)

BTW, I tried cherry picking 2cc44faf and  0fa9f08f

When I did ?&FEF8=65 the system hung.

Any thoughts?
