### ISSUE TITLE
Co Pro Life issue with the Pi 4

### ISSUE THREAD

**Issue by hoglet67** [hoglet67/PiTubeDirect#150]
The "large memory" version of Co Pro Life (*MLIFE) that uses the bank select register doesn't work on the Pi 4.

The failure is that pattern (even a small one) just stays fixed.

Here's a quick test matrix:

Pi Zero 2/3A+:
- Co Pro 0 (Fast 6502) - Works
- Co Pro 16 (Lib 6502) - Doesn't work (pattern stays fixed)
- Co Pro 24 (JIT 6502) - Works

Pi 4:
- Co Pro 0 (Fast 6502) - Doesn't work (pattern stays fixed)
- Co Pro 16 (Lib 6502) - Doesn't work (pattern stays fixed)
- Co Pro 24 (JIT 6502) - Doesn't work (pattern stays fixed)

The failure on all cases on Co Pro 16 is expected (?) because that Co Pro uses tube_parasite_write() rather than tube_parasite_write_banksel(), so the bank select registers are not present. It's possible this is deliberate; I don't recall.

The same failure happens on the Pi 4 on all of the 6502 Co Pro types; this suggests mapping of the banksel registers is somehow broken on the Pi 4.

This might relate in some way to #149 - but it affects all 6502 Co Pro types.

**Comment by dp111** [comment]
I wonder if after map_4k_page we need a data cache flush.

**Comment by dp111** [comment]
I don't know if page 13 is relevant here
https://developer.arm.com/documentation/epm012079/latest ?

**Comment by hoglet67** [comment]
> I don't know if page 13 is relevant here

Possibly, but I tried adding dmb AND isb after we invalidate the TLB (in map_4k_page) and it make no difference.

I've written a small test program in BASIC:
![capture40](https://user-images.githubusercontent.com/1951463/148545760-932706bb-299e-4208-a1e6-f7459bc38c19.png)

Here's the expected result of two runs after power up.
![capture34](https://user-images.githubusercontent.com/1951463/148545289-50d2df82-2c39-48cc-bd84-319551dd3aca.png)
![capture35](https://user-images.githubusercontent.com/1951463/148545303-b34b9176-c242-4164-b325-86171a22008b.png)

The 55555555 values are just what happens to be in memory at 256K on power up/

The 11223344 value is written into the default bank so it's easily identifieable.

This is indeed what you see on a Pi Zero 2 in both Co Pro 0 and Co Pro 24.

On the Pi 4, on Co Pro 0, the results look like:
![capture36](https://user-images.githubusercontent.com/1951463/148545312-ac06a57c-0ca8-4e03-85de-d2f3b6cb7ed3.png)
![capture37](https://user-images.githubusercontent.com/1951463/148545321-2ae942c9-f323-40dc-9313-cb3752394305.png)

So no evidence of banks switching occurring.

On the Pi 4, on Co Pro 24, the results look like:
![capture38](https://user-images.githubusercontent.com/1951463/148545333-12660144-4216-48b3-9a87-d254e5aff3ea.png)
![capture39](https://user-images.githubusercontent.com/1951463/148545345-80309838-d393-453b-baa7-32656b40798d.png)

There is some evidence of bank switching, but it's very delayed/eratic.

This is very likely to be data cache related, and is either:
1) The first bank that is read is cached, and remains in the data cache when the page table is changed
2) The page table is in the data cache, and when a page fault happens stale data from memory is read

Domimic. a couple of questions for you:

Concerning (1), it does seem like we need to clean/invalidate the 8K bank in memory, then wait fot this to be done (with a barrier) before we update the page table.

Concerning (2), is this possible? Surely the page table walk is happening "through" the data cache? It did occur to me that this might be configurable, and be different on the Pi 4. This does indeed seem to be configurable:
https://github.com/hoglet67/PiTubeDirect/blob/hognose-dev/src/cache.c#L321

**Comment by hoglet67** [comment]
According to the Cortex A72 technical manual (6-285 in the above link), the data cache is PIPT (physically indexed, physically cached), so I think that means that we don't have to worry about invalidating the 8K page in the data cache.

The Cortex A53 data cache is also PIPT

The ARM1176 data cache is VIPT, so possible (1) is an issue there?

**Comment by hoglet67** [comment]
DATA SYNCHRONIZATION BARRIER !!!

I suspect this waits for the TLB invalidate to complete before continuining. 

Not quite why this is so critical...

**Comment by hoglet67** [comment]
So one further comment on this....

It was the errata that Dominic linked to that highlighted the problem.

Specifically, it seems it is a ARM architectural requirement to perform a DSB after a TLB invalidate, otherwise the TLB invalidate might never be seen.

> The Arm architecture states that a separate observer might observe a write to the translation tables at any time after the execution of the instruction that performed that write. However, it also states that the write is only guaranteed to be observable after the execution of a DSB instruction by the PE that executed the instruction that performed the write to the translation tables.

(The errata further suggests an ISB might be necessary as well; that doesn't seem to be the case in our usage of this, at least not currently)

But on the Pi 4 a DSB is needed, a DMB and/or ISB is not sufficient.

I wonder if this affects anything else we are doing?

Also, I suspect we should be invalidating the TLB after updating the page table, not before????

**Comment by hoglet67** [comment]
The minimum change to make the TLB change visible seems to be:
```
DSB ISH
```
where ISH stands for "Inner Shared Domain"

**Comment by dp111** [comment]
I think this is a more generic version which matches the ARMv8 documentation and should support executing code in the future.
commit id : 5fd3e1105a5949a3c425b12471aa77f33196c5a5 and 64ad96c7bc97c2cc66e956b1d4e28832674361b5
