### ISSUE TITLE
6502 3 MHz issue in Gecko

### ISSUE THREAD

**Issue by mcnalu** [hoglet67/PiTubeDirect#158]
The symptoms of this issue are identical to those described in #66 in that after *FX 151,230,1 there is no cursor after a ctrl-break and no basic prompt after a break. All other co-pros seem to work just fine, including the default *FX 151,230,0.

I used the latest stable Gecko_fix1 and am using the level shifter board I just received from Retroclinic/Mark with my BBC Model B rev3 with TurboMMC and DNFS ROMs installed. The pi is connected only with a 40pin IDC cable and I checked and reseated all connections and the tube pins on the BBC are in near pristine condition.

I found the same problem with both my Pi 3B+ and Pi 2 and repeated ctrl-breaks never got it to work.

I then tried it with Hognose-rc2 and the problem was gone! Everything I've tried seems to work perfectly in Hognose-rc2 in fact.

**Comment by hoglet67** [comment]
Please can you pos a couple of photos of your setup, to save me asking loads of questions.

**Comment by mcnalu** [comment]
Voilà

![20220116_134859](https://user-images.githubusercontent.com/1899618/149662885-4039b68e-81f9-4380-8f43-13fde39a8117.jpg)
![20220116_134936](https://user-images.githubusercontent.com/1899618/149662887-7fdf72d6-1ace-4893-bd98-b02c29e563b4.jpg)

**Comment by RetroClinic** [comment]
Not sure if it's related, but I have had issues in the past, on the Elite attractor screen, where the occasional line was not removed after the next frame being drawn, leading to a build up of random lines on the screen. This has happened in Gecko sometimes as well, and under HN RC1. The fix before was to change the CPU in the beeb, as it seemed like it was a very slight timing issue with the PHI 1 Pin 3 output. The problem only occurred on the Model B, not the Master.

However, HN RC2 seems to have cleared it, and the CPUs that were causing the problem before are now working perfectly. Was this a known issue beforehand?

**Comment by hoglet67** [comment]
> Was this a known issue beforehand?

Not, I've not seen that before Mark.

**Comment by RetroClinic** [comment]
> Not, I've not seen that before Mark.

Ok, it didn't happen often, and before I just assumed it was bad timing off one particular CPU, as a swap would fix it. Next time I get a chance, I'll try and replicate it with RC1 and do a video, but as I said, it's fixed in RC2, so you've done something to sort it!

**Comment by hoglet67** [comment]
Whatever caused this seems to be fixed in hognose so closing.
