### ISSUE TITLE
ARM copro list doesn't adjust *FX 151 to 147 for Electron

### ISSUE THREAD

**Issue by mincebert** [hoglet67/PiTubeDirect#160]
Thought I'd just log this: whether you're bothered enough about it is another thing!

*HELP COPROS on the ARM native processor (15) doesn't adjust the header line to say "*FX 147..." instead of "*FX 151" (unlike the 6502 version).

**Comment by hoglet67** [comment]
*HELP COPROS works fine, but the issue is with CALL &2000.

This is now fixes in indigo-dev.
