### ISSUE TITLE
186 emulation.

### ISSUE THREAD

**Issue by stuaxo** [hoglet67/PiTubeDirect#162]
186 emulation would be interesting on this (and I guess from there it might be possible to emulate x86 processors that never saw the tube).

**Comment by hoglet67** [comment]
The existing x86 Co Pro uses Fake86 which already includes all the 80186 specific instructions.

Do you have any examples of programs that fail to run, which work on the original Acorn 80186 Co Processor?

Are you aware of any other emulation issues?

**Comment by stuaxo** [comment]
Nope, apologies it's aspirational for me to get a Beeb and PiTube at the moment... I'll definitely give it a go when I do though, I guess emulation opens up the possibility of running things that didn't run on the original, like apps for the 286 for instance.

**Comment by hoglet67** [comment]
No need to apologise - I just wanted to check that you hadn't hit a specific issue, as we are very close to a new release. If you are interested in the BBC Micro, it's definitely worth joining the startot forums:
https://stardot.org.uk/forums/

**Comment by stuaxo** [comment]
Cheers - I do go there and lurk from time to time, not as often as I'd like :)
