### ISSUE TITLE
Documentation: Pi 400 and other devices

### ISSUE THREAD

**Issue by greenonline** [hoglet67/PiTubeDirect#167]
### Pi 400

On the [releases page](https://github.com/hoglet67/PiTubeDirect/releases), under Hognose (Aug 31) a number of performance figures are listed for various Pi models. I wonder if it could be possible to add figures for the Pi 400 as it is marginally faster than the Pi 4.  Also is the Pi 400 even supported?

---

### Other Pi devices

In addition (and maybe this should be a seperate documentation issue), the [main Wiki page](https://github.com/hoglet67/PiTubeDirect/wiki) has headings and info for the [Pi Zero](https://github.com/hoglet67/PiTubeDirect/wiki#pi-zero) and the [Pi 3](https://github.com/hoglet67/PiTubeDirect/wiki#pi-3), and likewise in the **Overview** the Pi 3 and the Pi 1 are mentioned.

However, should there not be at least a mention of the other Pi devices (Pi 2, Pi 4, and Pi 400)? It is just that their absense makes one wonder (until seeing the releases page) whether it is *only* the Pi Zero and Pi 3 that are supported.

Trivial, admittedly, but maybe an update, or the addition of a section called **Supported Devices**, actually listing the supported Pi devices could be a good idea? Something like this:

>### Supported Devices
>
> - Pi 1
> - Pi 2
> - Pi 3
> - Pi 4
> - Pi 400
> - Pi Zero
> - Pi Zero 2

**Comment by hoglet67** [comment]
I've updated the [Supported Pi Models](https://github.com/hoglet67/PiTubeDirect/wiki/Supported-Pi-Models) page to indicate the supported/unsupported models re: the latest release (hognose).

The Pi 400 is not currently supported:
- it has a different hardware revision code that's not known to Hognose, so it won't be detected correctly
- the GPIO connector is a right angle connector and the board is larger, so it will not be physically compatible with most level shifters being sold

The main wiki page is unfortunately very out of date now, and it really needs a complete re-write. I've created a new issue for this: #168. 

I'll close this relating to the Pi 400
