### ISSUE TITLE
Frame Buffer: POINT's offscreen check is not right

### ISSUE THREAD

**Issue by BigEd** [hoglet67/PiTubeDirect#175]
Running lovebug's program at https://stardot.org.uk/forums/viewtopic.php?f=2&t=27265 doesn't work in PIVDU 2 mode. (It's a Langton's Ant program.)

A fairly minimal test in native ARM which involves moving the graphics origin:
```
*A.
*PIVDU 2
MODE 4
VDU 29,640;512;
PLOT 69,-50,-50
PRINT POINT(-50,-50)
```
The POINT returns -1 which indicates off-screen, and that's wrong.

**Comment by hoglet67** [comment]
We should make sure to fix this for Indigo!

**Comment by hoglet67** [comment]
Fixed in indigo-alpha2
