### ISSUE TITLE
Native ARM crashes when CALLing OSCLI from ARMBASIC if the string is a HELP command 

### ISSUE THREAD

**Issue by beebmaster** [hoglet67/PiTubeDirect#176]
As here:
![PanOSCALLBroken15](https://github.com/hoglet67/PiTubeDirect/assets/71549802/5a37cff1-9f93-4172-b970-ebcbc1eac199)

There appears to be a case, after a reset, where an error is returned instead:
![Screenshot 2023-09-04 23-27-26](https://github.com/hoglet67/PiTubeDirect/assets/71549802/00f8de4e-bf4c-4357-9754-6b15853a51af)

**Comment by RetroClinic** [comment]
I noticed this too, but wasn't it fixed with the Hognose update?

**Comment by hoglet67** [comment]
Mark, I don't actually recall this issue, or fixing it, but it seems you are right.

I can reproduce this with Gecko, but not with Hognose or Indigo. 

Ian, can you confirm what version of PiTubeDirect you are running?

**Comment by beebmaster** [comment]
Yes, you are quite right!  It works in Hognose, I just tested on Master 128 Station 112, which has a fairly new Pi Tube, with internal Retroclinic adapter, and it works.

Station 201 however is till on Gecko, where the problem exists.  The trouble there is that I have one of Ken's external adapters plugged into the Tube and it's stuck so I can't get it out to update the SD card!

**Comment by hoglet67** [comment]
Fixed in Hognose release.
