### ISSUE TITLE
Issue with 2022 version RPi 3A+

### ISSUE THREAD

**Issue by RetroClinic** [hoglet67/PiTubeDirect#204]
Hi.

I've taken delivery of some new RPi 3A+, and these seem to be slightly different, having a (C)2022 instead of (C)2018, and have some slight differences on the PCB.

![RPi 3A](https://github.com/hoglet67/PiTubeDirect/assets/38635598/20187022-a9f4-44d8-82ef-fea4616f199d)

However, none of the new ones will boot the firmware? I get the usual single flash of the green LED, followed by 4 long flashes and 7 quick flashes. I presume this is an error code of some description?

I've looked through the issues and new files, but can't seem to see any reference to an issue like this arising so far? I've tried it with the latest Indigo and it's doing the same thing on the 2022 version, but works fine on the 2018 one?

Thanks as always, Mark.

**Comment by hoglet67** [comment]
I'm not aware of a new 3A+ model, maybe Dominic is?

The 4-long 7-short error code is "Power Failure Type B":
https://www.raspberrypi.com/documentation/computers/configuration.html#led-warning-flash-codes

Is the 3.3V output from the Pi present?

Can you boot Raspberry Pi OS using an official PSU? If so, then login and cat /proc/cpuinfo and that will tell you the Pi revision code.

**Comment by RetroClinic** [comment]
Ok, that's a worrying error, as all of them (tested 8 so far) are doing the same thing. There is 3.31v where it should be, so that seems ok.

I'll try booting the Pi OS a bit later, thanks.

**Comment by dp111** [comment]
The firmware does need to be updated to support this board. This should go
into the indigo release.

**Comment by hoglet67** [comment]
Seems there is a new revision of the 3A+
[PCN-Raspberry-Pi-3A-Revision-2-PCB.pdf](https://github.com/hoglet67/PiTubeDirect/files/12892817/PCN-Raspberry-Pi-3A-Revision-2-PCB.pdf)

**Comment by hoglet67** [comment]
OK, I was planning a new indigo alpha shortly any way.

Any suggestion of a specific firmware revision, or should I just grab the latest?

Dominic, I'll merge you branch as well.

Dave

**Comment by dp111** [comment]
Just the latest should be fine.

**Comment by RetroClinic** [comment]
Yes, latest version of RPi OS boots just fine, so hopefully you guys have got it in hand, as always! I'll put them aside and wait for the new release and let you know.

Thanks. Mark.

**Comment by hoglet67** [comment]
Here's an updated Indigo build that includes the latest firmware blob:
https://github.com/hoglet67/PiTubeDirect/releases/tag/indigo-alpha4

Let us know if this resolves the issue.

**Comment by RetroClinic** [comment]
Yes, sorted! Booting up as normal now. Thanks again for the incredible support you do for this project, as well as the speed of the replies!
