### ISSUE TITLE
Native ARM: framebuffer *PIVDU "Bad command" in indigo-alpha5

### ISSUE THREAD

**Issue by mincebert** [hoglet67/PiTubeDirect#207]
Thanks for fixing the CoPro 24 framebuffer MODE crash but, sorry to bother you again, there's a regression in indigo-alpha5 with a bug not in alpha4...

Switching to the ARM Native CoPro 15 and executing `*PIVDU 2` works, and the new status of the Beeb and Pi VDU drivers is displayed, but then you always get a `Bad command` error.

Again, MOS 3.50, Pi 3A+ with the framebuffer enabled, filesystem is ADFS but I get the same error in MMFS.

**Comment by dp111** [comment]
should be fixed on Indigo-dev-dp. Also fixed another stack alignment issue

**Comment by hoglet67** [comment]
Thanks for the quick fix Dominic, and appologies for missing this on testing yesterday (I missed the stack alignment fixes also covered the Native ARM).

Here's an alpha6 release including the Bad Command fix:
https://github.com/hoglet67/PiTubeDirect/releases/tag/indigo-alpha6
