### ISSUE TITLE
Type 2/3 transfers are not working

### ISSUE THREAD

**Issue by hoglet67** [hoglet67/PiTubeDirect#21]
See this post, which includes a test case:
http://stardot.org.uk/forums/viewtopic.php?p=159143#p159143

**Comment by BigEd** [comment]
Just to note, we believe this only affects Econet which uses two-byte transfer modes.

**Comment by dp111** [comment]
Possible fixed on the dptest branch

**Comment by hoglet67** [comment]
Fixed in 6b863a87
