### ISSUE TITLE
(NS32k) read_n will corrupt the stack when 5-8 bytes requested

### ISSUE THREAD

**Issue by fordp2002** [hoglet67/PiTubeDirect#29]
I was just looking at the code that was crashing on Bas32f and I noticed a bug (Probably mine).

If you request more than 4 bytes it will try and copy it to a 4 byte variable on the stack corrupting the stack.

**Comment by hoglet67** [comment]
Looked carefully through the usage of this, and it should only be called when n=1, 2 or 4.

It will now output a warning if called with n > 4

**Comment by fordp2002** [comment]
Thanks, I guessed it was a latent bug not causing issues. Thanks for the fix however.

**Comment by dp111** [comment]
Might be worth not using memcopy here
