### ISSUE TITLE
80286 Co Pro fails to boot with Ctrl-Break

### ISSUE THREAD

**Issue by hoglet67** [hoglet67/PiTubeDirect#31]
The following is logged to the serial console:

Illegal opcode: 67 @ 0000:0DE2

Pressing break and typing DOS at the * prompt works OK.

**Comment by dp111** [comment]
Looks as though the memory has been overwritten.

**Comment by hoglet67** [comment]
What was happening was the language transfer was going to the wrong place, due to the INSB instruction using the SI register instead of the DI register.
