### ISSUE TITLE
80286 BBC BASIC won't list programs

### ISSUE THREAD

**Issue by BigEd** [hoglet67/PiTubeDirect#40]
Writing a short Basic program, LIST gives no output. LIST ,99 will work.
```
10 END
LIST
```
(Again, supposing a core bug is most likely.)

**Comment by hoglet67** [comment]
Ed, it's maybe worth checking the behaviour on the Matchbox. I seem to remember hitting this before, so it may actually be a BBC Basic bug. I have a vague recollection this was something todo with line endings.

**Comment by BigEd** [comment]
Good idea. Checked. Matchbox is OK...

**Comment by hoglet67** [comment]
FYI, I just confirmed this bug is not present in B-Em 2.2 / BBC Basic 4.6.1

**Comment by BigEd** [comment]
(Seems to be fixed if SBB is correct, as per #39)
