### ISSUE TITLE
Different speeds between Zero and Zero-W

### ISSUE THREAD

**Issue by RetroClinic** [hoglet67/PiTubeDirect#58]
Hi.

I've been trying the standard Zero v1.3 and the Zero-W v1.1, and the W, according to the Native ARM core, and the ClockSP tests seems to be coming from the suppliers clocked at 700Mhz, rather than the 1GHz that the regular Zero does. Is this a known thing for the firmware? Is it picking up the different Zeros, or are the CPUs on the W genuinely running at 700MHz, even though the suppliers say they're meant to be clocked to 1Ghz?

Thanks, Mark.

First Pic - Zero-W, second pic, standard v1.3 Zero
![rpi-zerow](https://user-images.githubusercontent.com/38635598/43082808-d750d5fc-8e8c-11e8-8349-ee7c29412f10.JPG)
![rpi-zero](https://user-images.githubusercontent.com/38635598/43082824-e14dc36c-8e8c-11e8-8c90-899126d4df77.JPG)

**Comment by hoglet67** [comment]
Hi Mark,

Until a couple of days ago I haven't had access to a Pi Zero W.

Can you confirm what release of the PiTubeDirect this is with?

Dave

**Comment by RetroClinic** [comment]
Hi.

This is diamondback. I've since picked up on the config.txt section

arm_freq=1000

However, removing the # from that line makes the CoPro not boot at all. The activity light comes on during power up, then it goes off as the beeb boots.

**Comment by dp111** [comment]
I spent a while fixing up PiW . Try the Eggeater build.

**Comment by RetroClinic** [comment]
Hi.

Aha, ok, tried that, and I do get the faster speeds, and it showing 1000Mhz in core 15. Ony thing is, the first time it ran, it didn't boot, I needed a second power cycle to get it started, then it seemed to run ok. Might have just been a glitch, so I'll try it on a few more units and let you know. 

Thanks for that!

Mark.
![rpi-zerow eggeater](https://user-images.githubusercontent.com/38635598/43092114-0106f856-8ea4-11e8-8322-6cf928093e6c.JPG)

**Comment by hoglet67** [comment]
Dom, I've experienced the Pi W not booting reliably with the RGBtoHDMI project.

It was fixed by updating to a more recent Rpi Firmware blob.

So probably we need to do that in PiTubeDirect as well.

Dave

**Comment by RetroClinic** [comment]
I've come across a Pi-W that will consistently not boot with Egg Eater firmware, but boots reliably with the Diamondback. I've done a video to show it if it helps?

https://www.youtube.com/watch?v=UdfyWa7VLX8

Thanks for all your work with this!

**Comment by hoglet67** [comment]
Hi Mark,

Now I have access to a Pi Zero W, I'll try to replicate this tomorrow.

Are you saying that with Egg-Eater RC0, some Pi Zero W's always boot, and other Pi Zero W's never boot? Or is it less consistent than that?

Does your level shifter make the Pi's serial port accessible on a header? 

Do you have a suitable Pi Serial cable?

If so, it would be interesting to switch over to the debug kernel (see comments in config.txt) and see whether in the non-booting case you get any debug output on the serial port.

Dave

**Comment by hoglet67** [comment]
OK, I've just watched the video again and I think I understand what's happening.

With Egg-Eater we use more a recent Rpi firmware blob (that supports the 3B+).

But it seems that new firmware is taking ~1.6 second to boot. Where as the previous firmware took only ~200ms to boot.

Hence, on initial power up the Master does not detect the Co Pro is present.

This boot delay is something we need to investigate, but it fixing it may be out of out hands. It seems almost all this time is prior to our kernel booting. i.e. It's the RPI Foundation firmware blob that's stalling. 

I'll need to bisect and try to work out when this issue was introduced. That's quite painful and time consuming.

Dave

**Comment by RetroClinic** [comment]
Hi. Yes, it seems inconsistent. I can experiment and use a larger cap in the reset circuit to extend the boot times, to see if that will help. I deleted the serial port on my converters, but I do have some of Sundby's ones that have it on. I'm not sure how to hook it up, but I can look into it.

I had to Google a "firmware blob" LOL but I know what you mean now. I've been reading stuff about Broadcom keeping some of it's stuff closed source. Seems they've done a Microsoft and bloated it with the W? Can you not use the original blob with the new firmware to force the 1GHz frequency? It's not like we need the Wireless functionality. I've no idea how it's put together, I'm in awe of you guys work! I'm sure you've thought of that already.

**Comment by hoglet67** [comment]
Mark,

If we can pin down the version of the "firmware blob" where this slow down was introduced, we can file a bug and it may well get fixed. They are quite responsive. It affects at least the normal Pi Zero as well, and likely all models.

You might want to think about re-adding the Serial header to your level shifter, as it enables some important end-user functionality.

Specifically, if you switch over to the debug kernel, most of the Co Processors then have in-built debug capability, so if you are developing new code that runs on a Co Processor, you can disassemble, single step, set break points and watch points, dump memory, dump the CPU registers, etc. You access all this via the serial port.

(The only two that don't are the Fast 6502 and the Native ARM)

This isn't well documented yet, but that's on the TODO list to improve for the Egg-Eater final release.
