### ISSUE TITLE
Software reset (bit 5 of FEE0) no longer level sensitive

### ISSUE THREAD

**Issue by hoglet67** [hoglet67/PiTubeDirect#63]
Setting bit 5 of FEE0 should hold the Co Pro in the reset state. It used to, but that's no longer the case.

This is the commit the broke things: aa6a4a13

This doesn't cause an issue on the Beeb, because the MOS never uses this bit. But the Atom Tube Host code does, and this particular bit of code works with Boa, but fails with Egg-Eater:
https://github.com/hoglet67/AtomTubeHost/blob/master/src/AtomHost.asm#L190

**Comment by hoglet67** [comment]
Hi Dominic,

I wonder if you have any thoughts in this issue.

Reverting the change to tube-ula.c does resolve it.

It's easy to work around in the AtomTubeHost, but it does seem a genuine bug in PiTubeDirect compared to the way the Tube ULA works.

Dave

**Comment by BigEd** [comment]
(Just checking: should this still be open?)

**Comment by hoglet67** [comment]
Yes, it's not a biggie, but it's not actually been fixed yet.

**Comment by dp111** [comment]
Fixed in indigo-alpha2
