### ISSUE TITLE
32016 Core Bug "invalid shift" running CLOCKSP

### ISSUE THREAD

**Issue by hoglet67** [hoglet67/PiTubeDirect#7]
Also during BAS32/CLOCKSP we get overruns and repeated characters on the screen.

Cause seems to be the logging of a 32016 Core Bug:

tube reset - copro 13
pc=00005EC5: Invalid shift of 000000DF for size 32
pc=00005EC5: Invalid shift of 000000DF for size 32
OVERRUN: A=1; D=20; RNW=1; NTUBE=0; nRST=1
OVERRUN: A=1; D=20; RNW=1; NTUBE=0; nRST=1
OVERRUN: A=1; D=20; RNW=1; NTUBE=0; nRST=1
OVERRUN: A=1; D=36; RNW=1; NTUBE=0; nRST=1
OVERRUN: A=1; D=39; RNW=1; NTUBE=0; nRST=1
OVERRUN: A=1; D=2E; RNW=1; NTUBE=0; nRST=1

Occurs in master and gpu.

A shift of &DF is -32 is outside the range specified here:
http://cpu-ns32k.net/files/ismanual.pdf

Probably we should relax this warning.

**Comment by BigEd** [comment]
Perhaps make all warning texts conditional, only included for a debug build?

**Comment by hoglet67** [comment]
Fixed in 1dfbe624b3860be894e5b33c265c4188889bac53 by allowing +- 32 without warning.

**Comment by hoglet67** [comment]
Fixed in 1dfbe624b3860be894e5b33c265c4188889bac53 by allowing +- 32 without warning.
