### ISSUE TITLE
Native ARM - *BASICxxxx bug

### ISSUE THREAD

**Issue by beebmaster** [hoglet67/PiTubeDirect#77]
Native ARM traps star commands beginning with "BASIC" and assumes the host BASIC language ROM is being requested.  E.g. trying to load BASIC 135 from disc with *BASIC135 will attempt to invoke 6502 BASIC and exit with the "This is not ARM code" error.

**Comment by hoglet67** [comment]
The Native ARM Co Pro doesn't special-case BASIC in any way, so this is probably the *BASIC command in the MOS being greedy.

Is this on a Master?

**Comment by beebmaster** [comment]
Yes, it's on a Master.  It may be the MOS although I would have thought it would check for end of line after "BASIC". I'll do some testing without a co-processor active to see what it does.

**Comment by beebmaster** [comment]
Mmm...looks to be a bug in MOS 3.20 but only with numbers. *BASIC9999 will just do *BASIC.  *BASICALLY will look in the filing system.

Can the Native ARM Tube trap *BASIC before it goes to the MOS?

**Comment by hoglet67** [comment]
> Can the Native ARM Tube trap *BASIC before it goes to the MOS?

And do what with it?

**Comment by beebmaster** [comment]
Sorry, what I meant was can it distinguish between *BASIC<cr> which it would pass to the MOS of course (or invoke ARM BASIC if it's been included in the build) and *BASICnnnn which it would pass to the filing system.

**Comment by hoglet67** [comment]
I'm not sure it can, at least not easily and cleanly.

The Native ARM Co Pro can either handle a command itself, or pass it to the host via OSCLI.

It's then upto the host how the command is handled.

What's wrong with typing */BASIC135?

**Comment by beebmaster** [comment]
That doesn't work, still tries to invoke BASIC.  (But it doesn't do that on other co-pros).

**Comment by BigEd** [comment]
For me, it's BAS135 not BASIC135.  I wonder if that's not merely to save a bit of typing.

**Comment by hoglet67** [comment]
Good point Ed - BASIC135 isn't even a legal filename on DFS (1 character too many)

**Comment by beebmaster** [comment]
Very true, and I am sure we would want to keep the filename within a 7 character limit for maximum filing system compatibility. But there is still a difference between the way the Native ARM handles commands beginning with "BASIC" and other processors.

I've attached a few screenshots.

![capture296](https://user-images.githubusercontent.com/71549802/95014222-5db75600-063d-11eb-9338-db7a110d30a8.png)
![capture297](https://user-images.githubusercontent.com/71549802/95014223-5e4fec80-063d-11eb-986d-ce4016788d77.png)
![capture298](https://user-images.githubusercontent.com/71549802/95014224-5ee88300-063d-11eb-975c-1af7e250eacc.png)
![capture299](https://user-images.githubusercontent.com/71549802/95014225-5ee88300-063d-11eb-9d58-0936b79a5b34.png)
![capture300](https://user-images.githubusercontent.com/71549802/95014227-5f811980-063d-11eb-9177-f2d5560bf9a6.png)

It looks like in all cases, any numeric characters after BASIC are ignored, and *BASIC is executed.
Also in all cases, any alphabetic character after BASIC are taken into account and the full command line is acted up.
Prefixing with a slash character always passes the full command line to the filing system, except with the Native ARM running where it still operates as if the slash doesn't exist: numeric suffix does *BASIC, alpha suffix does *commandline.

**Comment by hoglet67** [comment]
This is the code I think that's causing a difference in behavior with handling /
https://github.com/hoglet67/PiTubeDirect/blob/master/src/tube-swi.c#L512

JGH had a hand in this bit, and so did I, so I'll need to take another look.

**Comment by beebmaster** [comment]
It looks like *RUN and */ should be treated as a special case and always passed to the filing system, otherwise it's impossible to run a file which is the same name as an MOS command:

![m0capture296](https://user-images.githubusercontent.com/71549802/95020819-62900000-0665-11eb-965c-8166bf0481da.png)
![m0capture297](https://user-images.githubusercontent.com/71549802/95020820-63289680-0665-11eb-866a-1a23b3a5e809.png)

**Comment by hoglet67** [comment]
> It looks like *RUN and */ should be treated as a special case and always passed to the filing system, otherwise it's impossible to run a file which is the same name as an MOS command.

Agreed, and now fixed in gecko-dev

**Comment by beebmaster** [comment]
Confirmed fixed, thanks very much.
