### ISSUE TITLE
Move Kernel and Increase RAM Available to Co-Pros

### ISSUE THREAD

**Issue by beebmaster** [hoglet67/PiTubeDirect#78]
The kernel is loaded at &1F00000 which limits the RAM available to Co-pros to 32MB.

Moving the kernel would allow an increase in RAM available, eg. to &13000000, would give 256MB available to co-pros which support this amount of RAM like the Native ARM.

Kernel can be moved by altering the segment addresses in rpi.ld and the kernel address in config.txt.

Native ARM RAM, for example, can then be increased by altering the memory handlers in copro-armnative.c.

**Comment by hoglet67** [comment]
Fixed in gecko-dev (216MB available to Native ARM Environment)

**Comment by beebmaster** [comment]
Working beautifully, lovely.
