### ISSUE TITLE
Include ARM BASIC in the firmware

### ISSUE THREAD

**Issue by beebmaster** [hoglet67/PiTubeDirect#79]
ARM BASIC could be included in the Pi Tube firmware within programs.c and set to load above the highest value of HIMEM (&10000000 for a 256MB maximum co-pro RAM size) and below a relocated kernel (e.g. at &13000000), say at &12000000.

It could be called with an additional command included in tube-commands.c such as *ARMBASIC which would jump to the exec address.

ARM BASIC can be built from source with a very minor change to set VARS to &F800 which will increase PAGE to &10000, moving it out the way of the language being copied to co-pro RAM on a hard reset, and preventing any destruction of user RAM.

**Comment by hoglet67** [comment]
Now fixed in gecko-dev branch
