### ISSUE TITLE
Recalibrate "slow" cores to 3MHz before release of GPU code

### ISSUE THREAD

**Issue by hoglet67** [hoglet67/PiTubeDirect#8]

**Comment by BigEd** [comment]
For reference, I think the mechanism to be tuned is in the "waste_time" routine:
https://github.com/hoglet67/PiTubeDirect/search?q=waste_time

**Comment by hoglet67** [comment]
Fixed in 5b6322367882287e64f5b6ce457877bfdd2ccec1

Co Pro 1 calibrated to 3MHz on the Pi Zero, One, Two and Three.
